### ISSUE TITLE
[ERROR] [12/23/2016 11:08:13.258] [default-akka.actor.default-dispatcher-4]

### ISSUE THREAD

**Issue by thucnt** [renesca/renesca-magic-example#1]
I download build the project successfully. But I get this error when run it.
Error message: [akka://default/user/IO-HTTP/group-0/0] Aggregated response entity greater than configured limit of 1048576 bytes,closing connection

**Comment by cornerman** [comment]
Thanks for the report! The error message is because of the chunking of responses in spray. The default limit for an aggregated response is 1 MB. This triggered here, because the example initially queries the local neo4j instance, in order to find out whether the db is empty. This was done by querying the whole graph, which I have now updated to be limit 1.

It should work now, but feel free to reopen if the problem persists.

If you have this problem in an application of yours, you can set the limit in your `application.conf`:
```
# configure handling of chunked responses in spray
#spray.can.client.response-chunk-aggregation-limit = 0
spray.can.client.response-chunk-aggregation-limit = 10m
```
